import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function Header({ projectName = "Visual JSON Flow", status = "active", activeTab = "editor", onStatusChange, onTabChange }) {
    return (_jsxs("header", { className: "vjf-header", children: [_jsxs("div", { className: "vjf-header-left", children: [_jsxs("div", { className: "vjf-logo", children: [_jsxs("svg", { width: "24", height: "24", viewBox: "0 0 24 24", fill: "none", xmlns: "http://www.w3.org/2000/svg", children: [_jsx("path", { d: "M12 2L2 7L12 12L22 7L12 2Z", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" }), _jsx("path", { d: "M2 17L12 22L22 17", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" }), _jsx("path", { d: "M2 12L12 17L22 12", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" })] }), _jsx("span", { className: "vjf-logo-text", children: projectName })] }), _jsxs("div", { className: "vjf-tags", children: [_jsx("span", { className: "vjf-tag", children: "JSON Schema" }), _jsx("span", { className: "vjf-tag", children: "Visual Editor" })] })] }), _jsx("div", { className: "vjf-header-center", children: _jsxs("nav", { className: "vjf-nav", children: [_jsx("button", { className: `vjf-nav-item ${activeTab === 'editor' ? 'vjf-nav-active' : ''}`, onClick: () => {
                                console.log('Editor tab clicked');
                                onTabChange?.('editor');
                            }, children: "Editor" }), _jsx("button", { className: `vjf-nav-item ${activeTab === 'schema' ? 'vjf-nav-active' : ''}`, onClick: () => {
                                console.log('Schema tab clicked');
                                onTabChange?.('schema');
                            }, children: "Schema" }), _jsx("button", { className: `vjf-nav-item ${activeTab === 'preview' ? 'vjf-nav-active' : ''}`, onClick: () => {
                                console.log('Preview tab clicked');
                                onTabChange?.('preview');
                            }, children: "Preview" })] }) }), _jsxs("div", { className: "vjf-header-right", children: [_jsx("div", { className: "vjf-status", children: _jsxs("button", { className: `vjf-status-toggle ${status === 'active' ? 'vjf-status-active' : 'vjf-status-inactive'}`, onClick: () => onStatusChange?.(status === 'active' ? 'inactive' : 'active'), children: [_jsx("span", { className: "vjf-status-dot" }), status === 'active' ? 'Active' : 'Inactive'] }) }), _jsxs("div", { className: "vjf-actions", children: [_jsxs("button", { className: "vjf-action-button", children: [_jsxs("svg", { width: "16", height: "16", viewBox: "0 0 24 24", fill: "none", xmlns: "http://www.w3.org/2000/svg", children: [_jsx("path", { d: "M18 13V19A2 2 0 0 1 16 21H8A2 2 0 0 1 6 19V13", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" }), _jsx("path", { d: "M12 3V15", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" }), _jsx("path", { d: "M16 7L12 3L8 7", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" })] }), "Share"] }), _jsxs("div", { className: "vjf-saved-indicator", children: [_jsx("svg", { width: "16", height: "16", viewBox: "0 0 24 24", fill: "none", xmlns: "http://www.w3.org/2000/svg", children: _jsx("path", { d: "M20 6L9 17L4 12", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" }) }), "Saved"] })] })] })] }));
}
