name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: { node-version: [18.x, 20.x] }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable Corepack
        run: corepack enable
      - name: Verify Yarn version
        run: yarn --version
      - name: Install dependencies
        run: yarn install --immutable
      - name: Type check
        run: yarn typecheck
      - name: Build
        run: |
          echo "Building packages in sequence..."
          yarn workspace @vjf/core build
          echo "Core package built, checking dist..."
          ls -la packages/core/dist/
          yarn workspace @vjf/react build
          echo "React package built, checking dist..."
          ls -la packages/react/dist/
          yarn workspace visual-json-flow-demo build
