name: Deploy to GitHub Pages (Simple)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Enable Corepack
      run: corepack enable
      
    - name: Verify Yarn version
      run: yarn --version
      
    - name: Install dependencies
      run: yarn install --immutable
      
    - name: Build
      run: |
        echo "Building packages in sequence..."
        yarn workspace @vjf/core build
        echo "Core package built, checking dist..."
        ls -la packages/core/dist/
        yarn workspace @vjf/react build
        echo "React package built, checking dist..."
        ls -la packages/react/dist/
        yarn workspace visual-json-flow-demo build
      
    - name: Prepare demo directory
      run: |
        mkdir -p demo
        cp -r apps/demo/dist/* demo/
        cp index.html demo/
        
    - name: Deploy to GitHub Pages (Simple)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./demo
